### ISSUE TITLE
Update Database dialog does not appear

### ISSUE THREAD

**Issue by drjohnsonjr** [JetBrains/rider-efcore#158]
#### Describe the bug
When calling Tools: Entity Framework Core: Update Database, no dialog appears.

#### Expected behavior
Update Database dialog should appear.

### Environment (please complete the following information):
- OS: Windows 10 Enterprise
- .NET SDK info (installed ones and version used within Rider): 7.0.2
- Plugin version: 231.1.0
- Rider version: 2023.1

#### Additional context
Update Database worked before recent plugin and rider upgrades.

**Comment by seclerp** [comment]
Hi @drjohnsonjr, please collect logs via `Help | Collect logs` right after it happens and attach here (simple steps to reproduce will also work)

**Comment by drjohnsonjr** [comment]
Sorry, I don't feel comfortable about sharing logs.  I looked through the logs after trying to reproduce the problem and didn't see any reference to Entity Framework Core, and also didn't see any updates to log files when I requested Update Database.

But I can say that other EF Core dialogs work fine.  Generate SQL Script and Add Migration both open the correct dialog.   But using Tools: Entity Framework Core: Update Database does nothing.   No error, no dialog.

I also tried disabling all plugins except EF Core.  No change.

**Comment by seclerp** [comment]
You could share logs privately if opening non-public YouTrack issue works for you:  https://youtrack.jetbrains.com/newIssue?project=RIDER

**Comment by seclerp** [comment]
Also, could you check the error icon at the right-bottom side of the window? Does it have something related in the list of errors? 

![image](https://user-images.githubusercontent.com/20597871/230505030-5ad18d31-d2c5-4bcf-a7c6-5befaeab4caa.png)

**Comment by drjohnsonjr** [comment]
Yes, there is an error there.  See below.   I have line comments (//) in my appsettings.development.json.

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)
 at [Source: (File); line: 7, column: 6]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:749)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:673)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipComment(UTF8StreamJsonParser.java:3268)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:3148)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:3124)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1039)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:537)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:98)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:23)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4772)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3157)
	at me.seclerp.rider.plugins.efcore.features.connections.impl.AppSettingsConnectionProvider.getAvailableConnections(AppSettingsConnectionProvider.kt:30)
	at me.seclerp.rider.plugins.efcore.features.connections.DbConnectionsCollector.collect(DbConnectionsCollector.kt:35)
	at me.seclerp.rider.plugins.efcore.features.shared.ObservableConnections$initBinding$1.invoke(ObservableConnections.kt:19)
	at me.seclerp.rider.plugins.efcore.features.shared.ObservableConnections$initBinding$1.invoke(ObservableConnections.kt:17)
	at me.seclerp.observables.ObservableExKt$bind$1.invoke(ObservableEx.kt:9)
	at me.seclerp.observables.ObservableExKt$bind$1.invoke(ObservableEx.kt:8)
	at me.seclerp.observables.Event.invoke(Event.kt:17)
	at me.seclerp.observables.ObservableProperty$setter$1.invoke(ObservableProperty.kt:22)
	at me.seclerp.observables.ObservableProperty$setter$1.invoke(ObservableProperty.kt:18)
	at me.seclerp.observables.ObservableProperty.setValue(ObservableProperty.kt:14)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext.initData(CommonDataContext.kt:62)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDialogWrapper.initData(CommonDialogWrapper.kt:168)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDialogWrapper.initUi(CommonDialogWrapper.kt:88)
	at me.seclerp.rider.plugins.efcore.features.database.update.UpdateDatabaseDialogWrapper.<init>(UpdateDatabaseDialogWrapper.kt:53)
	at me.seclerp.rider.plugins.efcore.features.database.update.UpdateDatabaseAction.createDialog(UpdateDatabaseAction.kt:15)
	at me.seclerp.rider.plugins.efcore.features.database.update.UpdateDatabaseAction.createDialog(UpdateDatabaseAction.kt:9)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.openDialog(BaseCommandAction.kt:67)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.access$openDialog(BaseCommandAction.kt:27)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction$actionPerformed$1.run$lambda$0(BaseCommandAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

I removed the comments, restarted Rider, and tried again.   A different error now:

```
java.lang.NullPointerException
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext$initBindings$1.invoke(CommonDataContext.kt:37)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext$initBindings$1.invoke(CommonDataContext.kt:35)
	at me.seclerp.observables.ObservableExKt$bind$1.invoke(ObservableEx.kt:9)
	at me.seclerp.observables.ObservableExKt$bind$1.invoke(ObservableEx.kt:8)
	at me.seclerp.observables.Event.invoke(Event.kt:17)
	at me.seclerp.observables.ObservableProperty$setter$1.invoke(ObservableProperty.kt:22)
	at me.seclerp.observables.ObservableProperty$setter$1.invoke(ObservableProperty.kt:18)
	at me.seclerp.observables.ObservableProperty.setValue(ObservableProperty.kt:14)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext.initData(CommonDataContext.kt:70)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDialogWrapper.initData(CommonDialogWrapper.kt:168)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDialogWrapper.initUi(CommonDialogWrapper.kt:88)
	at me.seclerp.rider.plugins.efcore.features.database.update.UpdateDatabaseDialogWrapper.<init>(UpdateDatabaseDialogWrapper.kt:53)
	at me.seclerp.rider.plugins.efcore.features.database.update.UpdateDatabaseAction.createDialog(UpdateDatabaseAction.kt:15)
	at me.seclerp.rider.plugins.efcore.features.database.update.UpdateDatabaseAction.createDialog(UpdateDatabaseAction.kt:9)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.openDialog(BaseCommandAction.kt:67)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.access$openDialog(BaseCommandAction.kt:27)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction$actionPerformed$1.run$lambda$0(BaseCommandAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by seclerp** [comment]
Wonderful, thanks, I'll take a look

**Comment by OmarHamdan95** [comment]
When u will release the fix for it Please

**Comment by seclerp** [comment]
In a couple of days

**Comment by OmarHamdan95** [comment]
Thanks

**Comment by seclerp** [comment]
Done in [`231.1.1`](https://github.com/seclerp/rider-efcore/releases/tag/v231.1.1)
