### ISSUE TITLE
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory

### ISSUE THREAD

**Issue by golesmn** [JetBrains/rider-efcore#179]
When I use the ui tool for creating migrations and updating the db it says System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory.It works when I execute the same command from the terminal. I am currently on ubuntu 22.04

**To Reproduce**

1. Go to UI tools ''
2. Click on Update or Add migrations

#### Expected behavior
I wanted the migrations to run or make migrations but it is not happening using the tool but I can do that from the terminal

#### Screenshots

![image](https://github.com/JetBrains/rider-efcore/assets/136302849/16b76785-5e31-40af-8fb3-057f3191d354)

### Environment :

- OS: Ubuntu 22.04
- .NET SDK info (installed ones and version used within Rider): 6.0.408

- Plugin version: 232.0.0-rc1
- Rider version: 2023.2

**Comment by seclerp** [comment]
Hi @golesmn, thanks for the ticket. Please check that you have the proper .NET CLI configured in `Settings | Build, Execution, Deployment | Toolset and Build`.

**Comment by seclerp** [comment]
Hi @golesmn , thanks for the ticket. Please share your dialog setup before executing the command. Also, please uncheck "No build" checkbox, it should not be used unintentionally.

**Comment by golesmn** [comment]
![image](https://github.com/JetBrains/rider-efcore/assets/136302849/21e00eb5-8cb6-4a68-98be-ffcef1c07df0)
and the solution and the csproj are in the same directory
like this
![image](https://github.com/JetBrains/rider-efcore/assets/136302849/248d40e8-f3ea-4e33-b7b0-2cef78515eb2)

**Comment by golesmn** [comment]
> And also please share your solution layout. Where your .csproj files are located?

![image](https://github.com/JetBrains/rider-efcore/assets/136302849/3e51ab5e-2b6d-4a37-b1fb-7df44d8fc843) 

and the popup is like this
![image](https://github.com/JetBrains/rider-efcore/assets/136302849/3e02dd93-48a3-46be-bf47-f83239cf5577)

**Comment by seclerp** [comment]
When you click "Preview", which "Working directory" is shown?

**Comment by golesmn** [comment]
> When you click "Preview", which "Working directory" is shown?

working directory is correct. It is same as the working directory where the csproj and solution are located.

**Comment by haas-daniel** [comment]
I have the same problem. The command works if I run it manually from terminal window.

OS: Linux Mint 21.2
.NET SDK: 7.0.404
Rider: 2023.3 EAP7

**Comment by YaqubAliy02** [comment]
how to fix this problem pleasehelp me, when I add migrate I faced error like this.

**Comment by Prohor327** [comment]
I have the same problem. I use vscode.
OS: Arch Linux x86_64
.NET SDK: 8.0.107

**Comment by SandaruwanFdo** [comment]
Same problem in Rider 2024.2.2
OS : macOS sonoma 14.6.1 (23G93)
.Net : 6

**Comment by seclerp** [comment]
Hi folks, please add as many details about your cases as possible. Thank you.

@Prohor327 if your question is about `dotnet ef` in general and not about Rider, please forward it to .NET team.

**Comment by SandaruwanFdo** [comment]
> Same problem in Rider 2024.2.2 OS : macOS sonoma 14.6.1 (23G93) .Net : 6
Entity Framework Core UI Plugin : 242.21829.166

`/usr/local/share/dotnet/dotnet ef migrations add --project CloudLite.Repo/CloudLite.Repo.csproj --startup-project CloudLite/CloudLite.csproj --context CloudLite.Repo.Data.RepositoryContext --configuration Release AddHasFinance --output-dir Migrations/Development
System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/Users/sandaruwan/My Projects/Visual Studio/CloudLite/dotnet' with working directory '/Users/sandaruwan/My Projects/Visual Studio/CloudLite'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.EntityFrameworkCore.Tools.Exe.Run(String executable, IReadOnlyList`1 args, String workingDirectory, Boolean interceptOutput)
   at Microsoft.EntityFrameworkCore.Tools.Project.FromFile(String file, String buildExtensionsDir, String framework, String configuration, String runtime)
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Execute(String[] _)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
An error occurred trying to start process '/Users/sandaruwan/My Projects/Visual Studio/CloudLite/dotnet' with working directory '/Users/sandaruwan/My Projects/Visual Studio/CloudLite'. Exec format error

Process finished with exit code 1.
`

![Screenshot 2024-08-31 at 10 24 07 AM](https://github.com/user-attachments/assets/2a03e270-bfc9-49d7-9696-9db701d7d736)

Terminal command works normally

**Comment by seclerp** [comment]
Rider executes `dotnet ef` commands quite close to how they would be executed via the terminal. The main difference that may cause issues is environment on which Rider executable is running. It may have different `$PATH` and other variables defined.

So I suggest performing 2 checks:

### 1. Environment comparison

Please check your `$PATH` and other variables in your terminal profile and compare them to the Rider ones. Also, check for symlinks, according to the similar issue on efcore tooling side: https://github.com/dotnet/efcore/issues/16071

To validate which environment is used by Rider:
1. Find the "IDE Scripting Console" in Search Everywhere (<kbd>Shift</kbd>, <kbd>Shift</kbd>)
1. Type there `System.getenv("PATH")`
1. Press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>Enter</kbd>

More information about IDE Scripting Console could be found [here](https://www.jetbrains.com/help/idea/ide-scripting-console.html).

### 2. `dotnet` executable layout

Also, from `Exec format error` I can also suggest that for some reason `dotnet` executabe which is used by inner `dotnet ef` command may have unsupported process architecture. If you have ARM-based Apple chip please validate that your env in Rider uses an ARM version of the `dotnet` and vice versa in case of Intel chip.

In case it doesn't help you are welcome to report the issue to our issue tracker with full logs collected. The simplest way of doing it is a `Help | Report a Bug` option from the application menu. Please provide detailed steps to reproduce the issue. Thanks!

**Comment by ChekeGT** [comment]
Also having the same issue, but it seems that only dotnet-ef is on my path, but dotnet is'nt, how do we change the path on the IDE scripting console?

**Comment by ChekeGT** [comment]
Created  a symlink on /usr/local/bin cause that path was already registered on IDE scripting console. But i dont like the solution at all

**Comment by Icy-Thought** [comment]
I got it to work... somehow. Going to push an update to nixpkgs. Apologies for the long delay y'all!
